name: SlashRemind
main: com.battleasya.slashremind.SlashRemind
version: 1.0.0
author: Dennie
website: http://battleasya.com
description: A simple remind plugin.
commands:
  remind:
    description: Send reminder.
  remindreload:
    description: Reload config
permissions:
  remind.reload:
    default: op