name: SlashRemind
main: com.battleasya.slashremind.SlashRemind
version: 1.0.1
author: Dennie
website: http://battleasya.com
description: Remind Extension
commands:
  remind:
    description: Send reminder.
  remindreload:
    description: Reload config.
permissions:
  remind.*:
    default: op
    children:
      remind.use: true
      remind.reload: true